# -*- coding: utf-8 -*-
"""finance_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKf1e7zouavcPtO5hcGkMBZI81WR3gc-

# Capstone Project: Personal Finance Tracker
## Author: Serenity Smith
## [Link to Colab](https://colab.research.google.com/drive/1eKf1e7zouavcPtO5hcGkMBZI81WR3gc-?usp=sharing)
"""

expenses = {}

print("Welcome to My Personal Finance Tracker")

while True:
  choice = int(input("\nWhat would you like to do? \n1. Add Expense \n2. View All Expenses \n3. View Summary \n4. Exit \n"))

  if choice == 4:
    print("See you soon!")
    break

  if choice == 1:
    print("Adding an Expense")
    try:
      cat = input("Enter expense category: [e.g. Food] ")
      desc = input("Enter expense description: [e.g. Lunch] ")
      amt = float(input("Enter expense cost: $"))
    except ValueError:
      print("Enter a numerical value for the amount!")
    else:
      if cat in expenses:
        expenses[cat] += ((desc, amt),)
      else:
        expenses[cat] = ((desc, amt),)
      print("Expense added successfully.")

  if choice == 2:
    print("Viewing Expenses")
    for e,v in expenses.items():
      print(f"\nCategory: {e}")
      for i in v:
        print(f"{i[0]}: ${i[1]:.2f}")

  if choice == 3:
    print("Viewing Summary")
    for e, v in expenses.items():
      t = 0
      print(f"\n{e}:", end=" ")
      for i in v:
        t += i[1]
      print(f"${t:.2f}")